<?php
// $Id: media_youtube.module,v 1.1.4.38 2010/04/21 14:24:35 aaron Exp $

/**
 *  @file
 *  Media YouTube provides a stream wrapper and formatters for videos provided
 *  by YouTube, available at http://youtube.com/.
 *
 *  @TODO:
 *  Create a thumbnail importer for media styles/ image styles.
 *  Tie in YouTube API.
 *  Allow editors to search for videos to display on the browser.
 *  Allow editors to put in a youtube username to display on the browser.
 *  Allow editors to log in w/ their credentials.
 */

/**
 * Implement hook_menu().
 */
function media_youtube_menu() {
  $items['media/add/media_youtube'] = array(
    'title' => 'Add media from YouTube',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_youtube_add'),
    'access arguments' => array('administer media'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'media_youtube.admin.inc',
    'weight' => -1,
  );

  $items['media/add/media_youtube/upload'] = array(
    'title' => 'Upload Media to YouTube',
    'page callback' => 'media_youtube_upload',
    'access arguments' => array('administer media'),
    'file' => 'media_youtube.admin.inc',
  );

  $items['admin/content/media/add/media_youtube'] = $items['media/add/media_youtube'];
  return $items;
}

/**
 *  Create stream wrapper for YouTube videos.
 */
function media_youtube_stream_wrappers() {
  stream_wrapper_register('youtube', 'MediaYouTubeStreamWrapper');
  return array(
    'youtube' => array(
      'name' => t('YouTube videos'),
      'class' => 'MediaYouTubeStreamWrapper',
      'description' => t('Videos provided by YouTube.'),
    ),
  );
}

/**
 *  Implements hook_theme().
 */
function media_youtube_theme($existing, $type, $theme, $path) {
  global $base_url;
  global $base_path;
	
  return array(
    'media_youtube_preview_style_old' => array(
      'variables' => array('style' => NULL),
    ),
    'media_youtube_preview_style' => array(
      'variables' => array('field_type' => NULL, 'container_name' => NULL, 'style_name' => NULL),
    ),
    'media_youtube_field_formatter_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
    ),
    'media_youtube_embed' => array(
      'variables' => array('style_name' => NULL, 'uri' => NULL, 'alt' => NULL, 'title' => NULL),
    ),
    'media_youtube_styles' => array(
      'variables' => array('element' => NULL, 'style' => NULL),
    ),
    'media_youtube_upload' => array(
	  'variables' => array('url' => NULL, 'next_url' => $base_url . $base_path . 'media/add/media_youtube/upload', 'token' => NULL),
	  'template' => 'upload',
	),
  );
}

function theme_media_youtube_field_formatter_styles($variables) {
  $element = $variables['element'];
  $style = $variables['style'];
  $variables['file'] = $element['#item'];
  $variables['uri'] = $variables['file']['uri'];
  $variables['style_name'] = $style['name'];
  return theme('media_youtube_embed', $variables);
}

/**
 *  Implements hook_styles_containers().
 */
function media_youtube_styles_containers() {
  return array(
    'file' => array(
      'containers' => array(
        'media_youtube' => array(
          'label' => t('YouTube Styles'),
          'data' => array(
            'streams' => array(
              'youtube',
            ),
            'mimetypes' => array(
              'application/octet-stream',
            ),
          ),
          'weight' => 0,
          'filter callback' => 'media_youtube_formatter_filter',
          'themes' => array(
            'field_formatter_styles' => 'media_youtube_field_formatter_styles',
            'styles' => 'media_youtube_styles',
            'preview' => 'media_youtube_preview_style',
          ),
          'description' => t('YouTube Styles will display embedded YouTube videos and thumbnails to your choosing, such as by resizing, setting colors, and autoplay. You can !manage.', array('!manage' => l(t('manage your YouTube styles here'), 'admin/config/media/media-youtube-styles'))),
        ),
      ),
    ),
  );
}

function media_youtube_formatter_filter($variables) {
  if (isset($variables['object'])) {
    $object = $variables['object'];
    return (file_uri_scheme($object->uri) == 'youtube') && ($object->filemime == 'application/octet-stream');
  }
}

/**
 *  Implements hook_styles_styles().
 */
function media_youtube_styles_styles() {
  return array(
    'file' => array(
      'containers' => array(
        'media_youtube' => array(
          'styles' => array(
            'youtube_thumbnail' => array(
              'name' => 'youtube_thumbnail',
              'effects' => array(
                array('label' => t('Thumbnail'), 'name' => 'thumbnail', 'data' => array('thumbnail' => 1)),
                array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 100, 'height' => 75)),
              ),
            ),
            'youtube_preview' => array(
              'name' => 'youtube_preview',
              'effects' => array(
                array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 1)),
                array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 220, 'height' => 165)),
              ),
            ),
            'youtube_full' => array(
              'name' => 'youtube_full',
              'effects' => array(
                array('label' => t('Autoplay'), 'name' => 'autoplay', 'data' => array('autoplay' => 0)),
                array('label' => t('Resize'), 'name' => 'resize', 'data' => array('width' => 640, 'height' => 480)),
                array('label' => t('Full screen'), 'name' => 'fullscreen', 'data' => array('fullscreen' => 1)),
              ),
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 *  Implements hook_styles_presets().
 */
function media_youtube_styles_presets() {
  $presets = array(
    'file' => array(
      'square_thumbnail' => array(
        'media_youtube' => array(
          'youtube_thumbnail',
        ),
      ),
      'thumbnail' => array(
        'media_youtube' => array(
          'youtube_thumbnail',
        ),
      ),
      'small' => array(
        'media_youtube' => array(
          'youtube_preview',
        ),
      ),
      'large' => array(
        'media_youtube' => array(
          'youtube_full',
        ),
      ),
      'original' => array(
        'media_youtube' => array(
          'youtube_full',
        ),
      ),
    ),
  );
  return $presets;
}

function theme_media_youtube_preview_style($variables) {
  $variables['uri'] = variable_get('media_youtube_preview_uri', 'youtube://v/-jubiv7QUco');
  return theme('media_youtube_embed', $variables);
}

function theme_media_youtube_styles($variables) {
  $style = $variables['style'];
  $variables['file'] = $variables['object'];
  $variables['uri'] = $variables['object']->uri;
  $variables['style_name'] = $style['name'];
  return theme('media_youtube_embed', $variables);
}

function theme_media_youtube_embed($variables) {
  $preset_name = $variables['preset_name'];
  $preset = styles_containers_available_styles('file', 'media_youtube', $preset_name);
  $output = '';
  if (!empty($preset)) {
    // Build the URL for display.
    $uri = $variables['uri'];
    $wrapper = file_stream_wrapper_get_instance_by_uri($uri);
    $parts = $wrapper->get_parameters();
    $url = 'http://youtube.com/v/'. check_plain($parts['v']);

    $fullscreen_value = $autoplay = 'false';
    $in_browser = $thumbnail = FALSE;

    foreach ($preset['effects'] as $effect) {
      switch ($effect['name']) {
        case 'autoplay':
          $autoplay = $effect['data']['autoplay'] ? 'true' : 'false';
          break;
        case 'resize':
          $width = $effect['data']['width'];
          $height = $effect['data']['height'];
          break;
        case 'fullscreen':
          $fullscreen_value = $effect['data']['fullscreen'] ? 'true' : 'false';
          break;
        case 'thumbnail':
          $thumbnail = $effect['data']['thumbnail'];
      }
    }
    if (isset($variables['object']->override)) {
      $override = $variables['object']->override;
      if (isset($override['width'])) {
        $width = $override['width'];
      }
      if (isset($override['height'])) {
        $height = $override['height'];
      }
      if (isset($override['wysiwyg'])) {
        $thumbnail = TRUE;
      }
      if (isset($override['browser']) && $override['browser']) {
        $in_browser = TRUE;
        $thumbnail = TRUE;
      }
    }
    $width = isset($width) ? $width : 560;
    $height = isset($height) ? $height : 340;
    if ($thumbnail) {
      $output = theme('image', array(
        'path' => 'http://img.youtube.com/vi/'. check_plain($parts['v']) .'/0.jpg',
        'alt' => $variables['alt'],
        'title' => $variables['title'],
        'attributes' => array('width' => $width, 'height' => $height),
        'getsize' => FALSE,
      ));
      if ($in_browser) {
        // Add an overlay that says 'YouTube' to media library browser thumbnails.
        $output .= '<span />';
      }
    }
    else {
      $id = 'media-youtube-preview';
      $div_id = 'media-youtube-preview-wrapper';
      $flashvars = check_plain(drupal_http_build_query(array('playerMode' => 'embedded')));
      // <object width="425" height="344"><param name="movie" value="http://www.youtube.com/v/lZ-s3DRZJKY&hl=en&fs=1&"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/lZ-s3DRZJKY&hl=en&fs=1&" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="425" height="344"></embed></object>
      $output = <<<OUTPUT
<div id="$div_id"><object type="application/x-shockwave-flash" height="$height" width="$width" data="$url" id="$id"><param name="movie" value="$url" /><param name="allowScriptAcess" value="sameDomain"/><param name="quality" value="best"/><param name="allowFullScreen" value="$fullscreen_value"/><param name="bgcolor" value="#FFFFFF"/><param name="scale" value="noScale"/><param name="salign" value="TL"/><param name="FlashVars" value="$flashvars" /><param name="wmode" value="transparent" /></object></div>
OUTPUT;
    }
  }
  return $output;
}

/**
 * Implement hook_media_browser_plugins
 * @return unknown_type
 */
function media_youtube_media_browser_plugins() {
  $plugins = array();
  $path = drupal_get_path('module', 'media_youtube');
  module_load_include('inc', 'media_youtube', 'media_youtube.admin');
  $redirect = array('media/browser', array('query' => array('render' => 'media-popup')));
  $upload_form = drupal_get_form('media_youtube_add', $redirect);
  $plugins['media_youtube'] = array(
    '#title' => t('YouTube'),
    '#attached' => array(
      'js' => array($path . '/js/media_youtube.fromurl.js'),
      'css' => array($path . '/media_youtube.wysiwyg.css'),
    ),
    '#markup' => drupal_render($upload_form),
  );
  return $plugins;
}

/**
 *  Implements hook_media_parse().
 */
function media_youtube_media_parse($url, $options = array()) {
  $scheme = 'youtube://';
  preg_match('@youtube\.com/watch[#\?]v=([^"\& ]+)@i', $url, $matches);
  if (isset($matches[1])) {
    return file_stream_wrapper_uri_normalize($scheme . 'v/' . $matches[1]);
  }
  // @TODO: Validate for malformed youtube urls.
}
